#+STARTUP:indent
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="css/styles.css"/>
#+HTML_HEAD_EXTRA: <link href='http://fonts.googleapis.com/css?family=Ubuntu+Mono|Ubuntu' rel='stylesheet' type='text/css'>
#+HTML_HEAD_EXTRA: <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js" type="text/javascript"></script>
#+HTML_HEAD_EXTRA: <script src="js/navbar.js" type="text/javascript"></script>
#+OPTIONS: f:nil author:nil num:1 creator:nil timestamp:nil toc:nil html-style:nil tex:dvipng

#+TITLE: The 555 Piano
#+AUTHOR: C. Delport

#+BEGIN_HTML
  <div class="github-fork-ribbon-wrapper left">
    <div class="github-fork-ribbon">
      <a href="https://github.com/stcd11/9-SC-555">Fork me on GitHub</a>
    </div>
  </div>
<div id="stickyribbon">
    <ul>
      <li><a href="1_Lesson.html">Week1</a></li>
      <li><a href="2_Lesson.html">Week2</a></li>
      <li><a href="4_Lesson.html">Week3</a></li>
      <li><a href="5_Lesson.html">Week4</a></li>
      <li><a href="6_Lesson.html">Week5</a></li>
      <li><a href="assessment.html">Assessment</a></li>

    </ul>
  </div>
#+END_HTML
* COMMENT Use as a template
:PROPERTIES:
:HTML_CONTAINER_CLASS: activity
:END:
** Learn It
:PROPERTIES:
:HTML_CONTAINER_CLASS: learn
:END:

** Research It
:PROPERTIES:
:HTML_CONTAINER_CLASS: research
:END:

** Design It
:PROPERTIES:
:HTML_CONTAINER_CLASS: design
:END:

** Build It
:PROPERTIES:
:HTML_CONTAINER_CLASS: build
:END:

** Test It
:PROPERTIES:
:HTML_CONTAINER_CLASS: test
:END:

** Run It
:PROPERTIES:
:HTML_CONTAINER_CLASS: run
:END:

** Document It
:PROPERTIES:
:HTML_CONTAINER_CLASS: document
:END:

** Code It
:PROPERTIES:
:HTML_CONTAINER_CLASS: code
:END:

** Program It
:PROPERTIES:
:HTML_CONTAINER_CLASS: program
:END:

** Try It
:PROPERTIES:
:HTML_CONTAINER_CLASS: try
:END:

** Badge It
:PROPERTIES:
:HTML_CONTAINER_CLASS: badge
:END:

** Save It
:PROPERTIES:
:HTML_CONTAINER_CLASS: save
:END:

* Homework Tasks
:PROPERTIES:
:HTML_CONTAINER_CLASS: activity
:END:
** Research It: Synthesizers
:PROPERTIES:
:HTML_CONTAINER_CLASS: research
:END:
- Synthesizers have radically changed popular music since they were first widely used in the early 1970s; hardly a pop record is made these days without featuring an electronic keyboard of some kind. 

- A synthesizer (sometimes spelled "synthesiser") is an electronic keyboard that can generate or copy virtually any kind of sound, making it able to mimic the sound of a traditional instrument, such as a violin or piano, or create brand new, undreamed of sounds—like the crunch of footsteps on the surface of Mars or the noise blood cells make when they tumble through our veins. "Synthesize" means to make something new, often by putting it together from existing pieces. So we can think of a synthesizer as an electronic gadget that makes new sounds by piecing together "old" ones. To understand how it does that, we need to know more about sound and how different instruments produce it in different ways.

- Do some research into what makes one instrument sound different from another and then explain 'Waveshapes'

- *INCLUDE DIAGRAMS IN YOUR EXPLANATIONS.*

- Upload your work to [[https://bournetolearn.com][www.bournetolearn.com]]





